// Host launcher for the Ascend gemm_w4a4 pod.
//
// 3c-5: PTO-style variadic launch. Mirrors
// `pto-isa/demos/baseline/gemm_basic/csrc/host/utils.h` INVOKE_PTO_KERNEL
// pattern — no DeviceParams pack, no per-call aclrtMalloc/Memcpy/Free
// staging, no blocking aclrtSynchronizeStream.
//
// Pre-3c-5 each launch did:
//   aclrtMalloc(96 B, HUGE_FIRST)  ~80 µs
//   aclrtMemcpy(H2D, 96 B)         ~30 µs
//   aclrtlaunch_*(blockDim, stream, dev_params)
//   aclrtSynchronizeStream         ~120 µs  (waits for kernel)
//   aclrtFree                      ~30 µs
// ─────────────────────────────────────
// Total host overhead ~260 µs/call vs 57 µs device-side kernel time
// (msprof, 16 tiles). Wall MFU was 1.3 % only because of this path.
//
// 3c-5 path:
//   aclrtlaunch_*(blockDim, stream, act, wgt, …, m_total)
// ─────────────────────────────────────
// 11 pointers + 1 uint64_t pass through the auto-gen wrapper directly.
// Stream comes from c10_npu::getCurrentNPUStream at the torch op layer,
// so downstream ops on the same stream are properly serialized; the
// torch_npu framework handles lazy sync when the output tensor is read.
// No need for the launcher to sync.
//
// Expected impact: wall ~318 µs → ~75 µs (≈ kernel 57 µs + variadic
// launch ~15 µs + torch dispatch). Device-side kernel unchanged.
//
// Trade-offs:
//   - We rely on the caller supplying torch_npu's current stream. If
//     a future caller passes a stand-alone aclrtStream they own, they
//     must drive their own sync. The op binding
//     (csrc/python/host/svdquant_w4a4_op.cpp) already does this.
//   - The auto-gen wrapper `aclrtlaunch_svdquant_gemm_w4a4_kernel` is
//     regenerated by ascendc.cmake whenever the kernel function
//     signature in kernel_device.cpp changes. Keep the two arg lists
//     in sync.

#include "gemm_w4a4.h"

#include <acl/acl.h>
#include "aclrtlaunch_svdquant_gemm_w4a4_kernel.h"

namespace svdquant::ascend {

namespace {

// kBM mirrors device-side constexpr. Used to compute blockDim from
// caller-supplied m_total. If you change kBM in kernel_device.cpp,
// change it here too — keep the two in sync.
constexpr uint64_t kBM = 128;

}  // namespace

void gemm_w4a4(void* act, void* wgt,
               void* ascales, void* wscales,
               void* lora_act_in, void* lora_up,
               void* bias, void* wcscales,
               void* workspace, void* lora_buf, void* out,
               uint64_t m_total,
               void* stream) {
    auto raw_stream = static_cast<aclrtStream>(stream);

    // Grid M-major: blockDim AI cores, each processes one [kBM, N, K]
    // tile of out. Mix 1:2 → each block has 1 cube + 2 vec subblocks.
    const uint32_t blockDim = static_cast<uint32_t>(m_total / kBM);

    // Variadic launch — matches kernel_device.cpp's
    // svdquant_gemm_w4a4_kernel(act_in, wgt_in, …, out_in, m_total)
    // arg list 1-to-1. ACL forwards the pointers to the kernel as
    // GM_ADDR; the uint64_t passes through as a scalar arg.
    aclrtlaunch_svdquant_gemm_w4a4_kernel(
        blockDim, raw_stream,
        act, wgt, ascales, wscales,
        lora_act_in, lora_up, bias, wcscales,
        workspace, lora_buf, out,
        m_total);

    // No sync, no free — torch_npu owns the stream and will sync lazily
    // when the caller reads the output tensor. See pre-3c-5 commentary
    // above for what we used to do here.
}

}  // namespace svdquant::ascend
